# start by pulling the python image
FROM iesodias/python310:latest

# copy the requirements file into the image
COPY ./flask-app/app/requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# copy every content from the local file to the image
COPY flask-app/app/. /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

RUN ls -la

EXPOSE 5000

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

CMD ["app.py" ]