name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        run: |
          docker build . --file flask-app/app/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/bootcampapp:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/bootcampapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/bootcampapp:$(date +%s)
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bootcampapp


