name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        run: |
          pwd
          docker ps
          ls
          cd flask-app/app
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/bootcampapp:latest
          docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/bootcampapp:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/bootcampapp:$(date +%s)
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/bootcampapp


